spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: lyp66lyp
      driver-class-name: com.mysql.cj.jdbc.Driver

